namespace: kube-system
serviceAccount: kiam

server:
  serverTls: kiam-server-tls
  daemonsetName: kiam-server
  nodeRoleSelector: master
  serviceName: kiam-server

agent:
  agentTls: kiam-agent-tls
  daemonsetName: kiam-agent
  nodeRoleSelector: worker
  hostInterface: '!eth0'
