namespace: kube-system
serviceAccount: kiam
image: quay.io/uswitch/kiam:v3.0

server:
  assumeRoleArn: arn:aws:iam::617143659582:role/kiam-server
  serverTls: kiam-server-tls
  daemonsetName: kiam-server
  nodeLabel: kiam #Only run on the nodes that are labeled for the server process. The iptables rules created for kiam will break networking otherwise
  toleration: kiam-server-node #Nodes that run the server process must be tainted so that agents and other applications cannot run on them
  serviceName: kiam-server
  logLevel: debug

agent:
  agentTls: kiam-agent-tls
  daemonsetName: kiam-agent
  hostInterface: '!eth0' #make sure to quote if value contains special chars
  logLevel: debug
